name: Unit Tests Linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allow manually triggering from the actions tab
  workflow_dispatch:


env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

  # Enable colour output for GTEST and XML file generation
  GTEST_COLOR: yes
  GTEST_OUTPUT: xml:test-results/

jobs:
  build:
    # The CMake configure and build commands are platform agnostic anda should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest
    env:
      BOOST_VERSION: 1.79.0
      BOOST_PATH: ${{github.workspace}}/libraries
      BOOST_ROOT: ${{github.workspace}}/libraries/boost/boost
    
    steps:
    - uses: actions/checkout@v2

    - name: Install packages
      run: |
        sudo apt-get update && sudo apt-get upgrade
        sudo apt install ${{github.workspace}}/libraries/Packages/solid2.deb
        wget https://github.com/red-panda-productions/ipc-lib/releases/download/v1.2.0/ipclib.deb
        sudo apt install ./ipclib.deb
        sudo apt-get install libplib-dev
        sudo apt-get install libexpat1-dev
        sudo apt-get install libmysqlcppconn-dev
	   sudo apt-get install python3-distutils
      
    - name: Cache boost
      uses: actions/cache@v2
      id: cache-boost
      with:
        # Set the default path as the path to cache
        path: ${{env.BOOST_ROOT}}
        # Use the version as the key to only cache the correct version
        key: boost-${{env.BOOST_VERSION}}-${{runner.os}}

    - name: Install boost
      if: steps.cache-boost.outputs.cache-hit != 'true'
      uses: MarkusJx/install-boost@v2.3.0
      id: install-boost
      with:
        boost_version: ${{env.BOOST_VERSION}}
        toolset: gcc
        platform_version: 20.04
        boost_install_dir: ${{env.BOOST_PATH}}
        
    - name: Install MySQL
      uses: Fettpet/setup-mysql@v1
      with:
        mysql-version: 8.0
        username: SDATest
        password: PASSWORD  
        
    - name: Configure CMake
      run: cmake -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -DOPTION_GITHUB_ACTIONS=ON -DCMAKE_C_FLAGS="-pthread" -DCMAKE_CXX_FLAGS="-pthread" -DBoost_INCLUDE_DIR=${{env.BOOST_ROOT}}/include -DBoost_LIBRARY_DIRS=${{env.BOOST_ROOT}}/lib -S ${{github.workspace}}/SDALib-CPP -B ${{github.workspace}}/build

    - name: Build
      working-directory: ${{github.workspace}}/build
      run: cmake --build .

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -V

    - name: Upload test results
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: test_results_xml
        path: ${{runner.workspace}}/build/SDATests/test-results/**/*.xml
